# --- AUTHENTICATION ---

### Obtain JWT Token
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "whoami",
    "password": 2011
}

### Refresh JWT Token
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDkzNTgzLCJpYXQiOjE3NDkwODk5ODMsImp0aSI6IjU4NjE1YzE3NTdlYTQzZGNiYTJhNTExNTFjOWQ5YmQ3IiwidXNlcl9pZCI6Mn0.KhcZgtj_-5lzOJmH2V6nDaNkjgEUMKbcPXlZDBrUqy4"
}

# --- PRODUCTS ---

### List all products
GET http://127.0.0.1:8000/api/products/ HTTP/1.1

### name Filter
GET http://127.0.0.1:8000/api/products/?name__icontains=Logiteck HTTP/1.1

### price filter
GET http://127.0.0.1:8000/api/products/?price__gt=200.00 HTTP/1.1

### search filter
GET http://127.0.0.1:8000/api/products?search="iphone" HTTP/1.1

### ordering filter
GET http://127.0.0.1:8000/api/products?ordering=price HTTP/1.1


### Retrieve a single product
GET http://127.0.0.1:8000/api/products/3/ HTTP/1.1

### Create a new product (correct endpoint)
POST http://127.0.0.1:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MTcxMjk5LCJpYXQiOjE3NDkxNjc2OTksImp0aSI6IjNlMzM2YjQ5N2M3YTQ0NTc4ODZkNTk0ZTgxYmRmMTYzIiwidXNlcl9pZCI6Mn0.1j2PLaRFH9dHRRWnHMe6IVZAYLLO-cfEExs-gGIMrcM

{
    "name": "New Product",
    "description": "This is a new product.",
    "price": 19.99,
    "stock": 10,
    "image": null
}

### Update an existing product
PUT http://127.0.0.1:8000/api/products/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDkzOTMyLCJpYXQiOjE3NDkwOTAzMzIsImp0aSI6ImQ3ODhkY2E2ZjYyODQyN2U4NDA3ZGQyMzYwNzYzYTUzIiwidXNlcl9pZCI6Mn0.lFZ6xasp6m_4j_CBPcyUHqA7RwCfDINn77WVMMztHv8

{
    "name": "New Product",
    "description": "This is a new product.",
    "price": 19.99,
    "stock": 100,
    "image": null
}

### Delete a product
DELETE http://127.0.0.1:8000/api/products/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDkzOTMyLCJpYXQiOjE3NDkwOTAzMzIsImp0aSI6ImQ3ODhkY2E2ZjYyODQyN2U4NDA3ZGQyMzYwNzYzYTUzIiwidXNlcl9pZCI6Mn0.lFZ6xasp6m_4j_CBPcyUHqA7RwCfDINn77WVMMztHv8
